title: ECE 4160 - Fast Robots
description: Course lab site for ECE 4160
author_name: Marcel Pantin
# No theme - using custom Bootstrap layout in _layouts
baseurl: "/FastRobots-2026"  # use "" if this is your username.github.io repo
# url: "https://yourusername.github.io"
